# Todo API Contract
# Defines the RESTful endpoints for Todo operations

openapi: 3.0.0
info:
  title: Todo API
  version: 1.0.0
  description: RESTful API for Todo operations with user isolation
servers:
  - url: http://localhost:8000/api/v1
    description: Local development server

paths:
  /todos:
    get:
      summary: Get all todos for authenticated user
      description: Retrieve a list of todos that belong to the authenticated user
      security:
        - BearerAuth: []
      responses:
        '200':
          description: Successful response with user's todos
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Todo'
        '401':
          $ref: '#/components/responses/UnauthorizedError'

    post:
      summary: Create a new todo
      description: Create a new todo item for the authenticated user
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TodoCreate'
      responses:
        '201':
          description: Todo created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Todo'
        '400':
          $ref: '#/components/responses/BadRequestError'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '422':
          $ref: '#/components/responses/ValidationError'

  /todos/{id}:
    get:
      summary: Get a specific todo
      description: Retrieve a specific todo by ID, must belong to authenticated user
      security:
        - BearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Successful response with the todo
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Todo'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '404':
          $ref: '#/components/responses/NotFoundError'

    put:
      summary: Update a todo
      description: Update an existing todo, must belong to authenticated user
      security:
        - BearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TodoUpdate'
      responses:
        '200':
          description: Todo updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Todo'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '404':
          $ref: '#/components/responses/NotFoundError'
        '422':
          $ref: '#/components/responses/ValidationError'

    patch:
      summary: Partially update a todo
      description: Partially update an existing todo, must belong to authenticated user
      security:
        - BearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TodoUpdate'
      responses:
        '200':
          description: Todo updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Todo'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '404':
          $ref: '#/components/responses/NotFoundError'
        '422':
          $ref: '#/components/responses/ValidationError'

    delete:
      summary: Delete a todo
      description: Delete an existing todo, must belong to authenticated user
      security:
        - BearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '204':
          description: Todo deleted successfully
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '404':
          $ref: '#/components/responses/NotFoundError'

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    Todo:
      type: object
      required:
        - id
        - title
        - user_id
        - created_at
        - updated_at
      properties:
        id:
          type: string
          format: uuid
          description: Unique identifier for the todo
        title:
          type: string
          maxLength: 255
          minLength: 1
          description: Title of the todo item
        description:
          type: string
          nullable: true
          description: Optional description of the todo item
        is_completed:
          type: boolean
          default: false
          description: Whether the todo item is completed
        user_id:
          type: string
          format: uuid
          description: ID of the user who owns this todo
        created_at:
          type: string
          format: date-time
          description: Timestamp when the todo was created
        updated_at:
          type: string
          format: date-time
          description: Timestamp when the todo was last updated

    TodoCreate:
      type: object
      required:
        - title
      properties:
        title:
          type: string
          maxLength: 255
          minLength: 1
          description: Title of the todo item
        description:
          type: string
          nullable: true
          description: Optional description of the todo item
        is_completed:
          type: boolean
          default: false
          description: Whether the todo item is completed (default: false)

    TodoUpdate:
      type: object
      properties:
        title:
          type: string
          maxLength: 255
          minLength: 1
          nullable: true
          description: Updated title of the todo item
        description:
          type: string
          nullable: true
          description: Updated description of the todo item
        is_completed:
          type: boolean
          nullable: true
          description: Updated completion status of the todo item

  responses:
    UnauthorizedError:
      description: Unauthorized - Missing or invalid JWT token
      content:
        application/json:
          schema:
            type: object
            properties:
              detail:
                type: string
                example: "Not authenticated"

    NotFoundError:
      description: Resource not found - Either the todo doesn't exist or belongs to another user
      content:
        application/json:
          schema:
            type: object
            properties:
              detail:
                type: string
                example: "Todo not found"

    BadRequestError:
      description: Bad request - Invalid input data
      content:
        application/json:
          schema:
            type: object
            properties:
              detail:
                type: string
                example: "Invalid input data"

    ValidationError:
      description: Validation error - Input doesn't meet requirements
      content:
        application/json:
          schema:
            type: object
            properties:
              detail:
                type: array
                items:
                  type: object
                  properties:
                    loc:
                      type: array
                      items:
                        type: string
                    msg:
                      type: string
                    type:
                      type: string