openapi: 3.0.3
info:
  title: Todo Application Authentication API
  description: Authentication endpoints for user registration, login, and JWT-based access control
  version: 1.0.0
  contact:
    name: Todo App Team
    email: support@todoapp.com

servers:
  - url: http://localhost:8000
    description: Local development server
  - url: https://api.todoapp.com
    description: Production server

tags:
  - name: Authentication
    description: User registration and authentication endpoints

paths:
  /auth/signup:
    post:
      tags:
        - Authentication
      summary: User registration
      description: Create a new user account with email and password
      operationId: signup
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - password
              properties:
                email:
                  type: string
                  format: email
                  description: User's email address
                  example: user@example.com
                password:
                  type: string
                  minLength: 8
                  description: User's password
                  example: MySecurePassword123!
      responses:
        '201':
          description: User successfully registered
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: User registered successfully
                  user:
                    $ref: '#/components/schemas/UserResponse'
        '400':
          description: Invalid input data
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Invalid email format
        '409':
          description: User already exists
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Email already registered

  /auth/signin:
    post:
      tags:
        - Authentication
      summary: User authentication
      description: Authenticate user with email and password, returns JWT token
      operationId: signin
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - password
              properties:
                email:
                  type: string
                  format: email
                  description: User's email address
                  example: user@example.com
                password:
                  type: string
                  description: User's password
                  example: MySecurePassword123!
      responses:
        '200':
          description: Authentication successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  access_token:
                    type: string
                    description: JWT access token
                    example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
                  token_type:
                    type: string
                    default: bearer
                    example: bearer
                  expires_in:
                    type: integer
                    description: Token expiration time in seconds
                    example: 86400
        '401':
          description: Invalid credentials
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Invalid email or password

  /auth/me:
    get:
      tags:
        - Authentication
      summary: Get current user information
      description: Retrieve information about the currently authenticated user
      operationId: getCurrentUser
      security:
        - BearerAuth: []
      responses:
        '200':
          description: Current user information
          content:
            application/json:
              schema:
                type: object
                properties:
                  user:
                    $ref: '#/components/schemas/UserResponse'
        '401':
          description: Unauthorized - invalid or missing JWT token
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Not authenticated

  /auth/logout:
    post:
      tags:
        - Authentication
      summary: User logout
      description: Invalidate the current JWT token
      operationId: logout
      security:
        - BearerAuth: []
      responses:
        '200':
          description: Logout successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Successfully logged out
        '401':
          description: Unauthorized - invalid or missing JWT token
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Not authenticated

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: JWT token for authentication

  schemas:
    UserResponse:
      type: object
      properties:
        id:
          type: string
          format: uuid
          description: Unique user identifier
          example: 550e8400-e29b-41d4-a716-446655440000
        email:
          type: string
          format: email
          description: User's email address
          example: user@example.com
        created_at:
          type: string
          format: date-time
          description: Account creation timestamp
          example: 2026-01-09T10:30:00Z

security:
  - BearerAuth: []

x-api-conventions:
  authentication:
    type: JWT
    algorithm: HS256
    expiration: 24 hours
    storage: HttpOnly cookies (recommended)
  error_handling:
    format: JSON
    status_codes:
      400: Bad Request (validation errors)
      401: Unauthorized (authentication required)
      403: Forbidden (insufficient permissions)
      409: Conflict (duplicate resource)
      500: Internal Server Error
  rate_limiting:
    signup: 5 attempts per hour per IP
    signin: 10 attempts per minute per IP
    global: 1000 requests per minute per IP